// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/ticker.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_proto_ticker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_proto_ticker_proto_rawDescGZIP(), []int{0}
}

func (x *Ticker) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_ticker_proto protoreflect.FileDescriptor

const file_proto_ticker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ticker.proto\x12\x06crypto\"l\n" +
	"\x06Ticker\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB0Z.github.com/Ryan-Diep/cloud-arbitrage/pkg/modelb\x06proto3"

var (
	file_proto_ticker_proto_rawDescOnce sync.Once
	file_proto_ticker_proto_rawDescData []byte
)

func file_proto_ticker_proto_rawDescGZIP() []byte {
	file_proto_ticker_proto_rawDescOnce.Do(func() {
		file_proto_ticker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticker_proto_rawDesc), len(file_proto_ticker_proto_rawDesc)))
	})
	return file_proto_ticker_proto_rawDescData
}

var file_proto_ticker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ticker_proto_goTypes = []any{
	(*Ticker)(nil), // 0: crypto.Ticker
}
var file_proto_ticker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ticker_proto_init() }
func file_proto_ticker_proto_init() {
	if File_proto_ticker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticker_proto_rawDesc), len(file_proto_ticker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ticker_proto_goTypes,
		DependencyIndexes: file_proto_ticker_proto_depIdxs,
		MessageInfos:      file_proto_ticker_proto_msgTypes,
	}.Build()
	File_proto_ticker_proto = out.File
	file_proto_ticker_proto_goTypes = nil
	file_proto_ticker_proto_depIdxs = nil
}
